'use client';

import Link from 'next/link';
import {useLocale, useTranslations} from 'next-intl';
import {motion} from 'framer-motion';
import {Activity, Bell, Calendar, Car, Check, ChevronDown, Cpu, Crown, HeartPulse, Home, MessageCircle, PawPrint, ShieldCheck, Sparkles, Star, Stethoscope, Users, Wifi, Scissors, BarChart3} from 'lucide-react';
import {useState} from 'react';
import CatLogo from './CatLogo';

const services = [
  [Home, 'Smart Boarding', 'Monitored accommodations with 24/7 technology oversight and live status updates.'],
  [Crown, 'Luxury Suites', 'Private premium rooms designed for comfort, enrichment, and complete relaxation.'],
  [HeartPulse, 'Daily Care', 'Feeding schedules, wellness checks, and activity time — all logged and reported.'],
  [BarChart3, 'Smart Monitoring', 'AI-powered litter box intelligence tracking behavior, health patterns, and alerts.'],
  [Scissors, 'Grooming', 'Professional grooming by trained specialists — your cat leaves looking their best.'],
  [Car, 'Transportation', 'Safe, comfortable pickup and drop-off with live tracking and arrival confirmation.'],
];
const servicesAr = [
  [Home, 'فندقة ذكية', 'إقامة مراقبة تقنيًا على مدار الساعة مع تحديثات مباشرة.'],
  [Crown, 'أجنحة فاخرة', 'غرف خاصة مصممة للراحة والهدوء وإثراء تجربة القطة.'],
  [HeartPulse, 'رعاية يومية', 'جداول تغذية وفحوصات راحة ونشاط موثقة يوميًا.'],
  [BarChart3, 'مراقبة ذكية', 'ذكاء لصندوق الرمل لمتابعة السلوك والمؤشرات الصحية والتنبيهات.'],
  [Scissors, 'العناية والتجميل', 'جلسات عناية احترافية ومريحة تناسب طبيعة القطة.'],
  [Car, 'النقل', 'استلام وتسليم آمن ومريح مع تأكيد الوصول.'],
];
const suites = [
  ['🏠','Standard Suite','SAR 80','Smart litter box monitoring','Daily feeding & care','WhatsApp updates','Play area access'],
  ['🌟','Premium Suite','SAR 120','All Standard features','Private enrichment space','Photo updates daily','Priority staff attention'],
  ['👑','VIP Royal Suite','SAR 200','All Premium features','Private luxury room','Dedicated caretaker','Video call sessions'],
];
const suitesAr = [
  ['🏠','الجناح القياسي','80 ريال','مراقبة صندوق الرمل الذكي','تغذية ورعاية يومية','تحديثات واتساب','الوصول لمنطقة اللعب'],
  ['🌟','الجناح المميز','120 ريال','كل مزايا القياسي','مساحة إثراء خاصة','صور يومية','اهتمام أولوية من الفريق'],
  ['👑','الجناح الملكي VIP','200 ريال','كل مزايا المميز','غرفة فاخرة خاصة','مسؤول رعاية مخصص','جلسات اتصال مرئي'],
];
const why = [
  [Wifi,'24/7 Monitoring','Smart sensors and continuous oversight around the clock.'],
  [Crown,'Luxury Environment','Premium suites designed for feline wellbeing.'],
  [Cpu,'Smart Technology','AI-powered insights no traditional pet hotel can match.'],
  [Stethoscope,'Vet Support','Veterinary consultation available on call.'],
  [Users,'Expert Staff','Trained cat care specialists.'],
  [MessageCircle,'WhatsApp-First','All updates arrive where you already are.'],
];
const whyAr = [
  [Wifi,'مراقبة 24/7','حساسات ذكية ومتابعة مستمرة طوال اليوم.'],
  [Crown,'بيئة فاخرة','أجنحة مميزة مصممة لراحة القطط.'],
  [Cpu,'تقنية ذكية','رؤى بالذكاء الاصطناعي لا توفرها الفنادق التقليدية.'],
  [Stethoscope,'دعم بيطري','استشارة بيطرية متاحة عند الحاجة.'],
  [Users,'فريق متخصص','مختصون مدربون في رعاية القطط.'],
  [MessageCircle,'واتساب أولًا','كل التحديثات تصلك في المكان المعتاد.'],
];

export default function LandingPage(){
 const t=useTranslations(); const locale=useLocale(); const ar=locale==='ar'; const [faq,setFaq]=useState(0);
 const S=ar?servicesAr:services; const R=ar?suitesAr:suites; const W=ar?whyAr:why;
 const other=ar?'/en':'/ar';
 const steps=ar?['اختر الجناح','اختر التواريخ','معلومات القطة','ملاحظات طبية','خدمات إضافية','دفع آمن','تأكيد واتساب']:['Select Room','Choose Dates','Cat Info','Medical Notes','Add Services','Pay Securely','WhatsApp Confirm'];
 const faqs=ar?[
  ['كيف تعمل مراقبة صندوق الرمل الذكي؟','يتابع النظام عدد الزيارات والوقت والأنماط السلوكية، ويرسل تنبيهًا عبر واتساب عند وجود تغيير مهم.'],
  ['كيف أحجز إقامة؟','من الموقع خلال 7 خطوات بسيطة: اختيار الجناح، التواريخ، معلومات القطة، ثم الدفع والتأكيد عبر واتساب.'],
  ['هل يوجد دعم بيطري؟','نعم، يوجد دعم بيطري عند الحاجة، ويتم التواصل معك فورًا قبل أي إجراء.'],
  ['كم مرة تصلني التحديثات؟','تصلك رسائل عند الوصول، وتحديثات يومية، وتنبيهات فورية عند وجود ملاحظة مهمة.']
 ]:[
  ['How does smart litter box monitoring work?','The system tracks frequency, timing and behavioral patterns, then sends a WhatsApp alert when there is a meaningful change.'],
  ['How do I book a stay?','Book in 7 simple steps: choose a suite, select dates, add cat information, pay and receive WhatsApp confirmation.'],
  ['What if my cat needs veterinary attention?','Vet support is available when needed, and we contact you immediately before any action.'],
  ['How often will I receive WhatsApp updates?','You receive check-in messages, daily reports, and real-time alerts when something important changes.']
 ];
 return <main className="min-h-screen bg-[var(--navy)] overflow-hidden">
  <nav className="sticky top-0 z-50 bg-[rgba(4,4,94,.92)] backdrop-blur border-b border-white/10"><div className="container h-20 flex items-center justify-between"><Link href={`/${locale}`} className="flex items-center gap-2"><span className="w-10 h-10 rounded-xl bg-[var(--lime)] text-[var(--navy)] grid place-items-center"><CatLogo className="w-6 h-6"/></span><span className="display text-3xl text-white">CatSafe</span></Link><div className="hidden md:flex items-center gap-7 text-sm text-white/70"><a href="#services">{t('nav.services')}</a><a href="#tech">{t('nav.tech')}</a><a href="#suites">{t('nav.suites')}</a><a href="#booking">{t('nav.booking')}</a><a href="#faq">{t('nav.faq')}</a></div><div className="flex gap-2"><Link className="btn btn-outline !py-2 !px-4" href={other}>{t('nav.switch')}</Link><a href="#booking" className="btn btn-lime !py-2 !px-4">{t('nav.book')}</a></div></div></nav>
  <section className="relative min-h-[calc(100vh-80px)] grid-bg"><div className="absolute -top-32 -end-32 w-[560px] h-[560px] rounded-full bg-[rgba(185,250,60,.08)]"/><div className="container py-20 lg:py-28 grid lg:grid-cols-2 gap-14 items-center relative"><motion.div initial={{opacity:0,y:20}} animate={{opacity:1,y:0}}><div className="eyebrow mb-5 inline-flex items-center gap-2"><Sparkles size={16}/>{t('hero.eyebrow')}</div><h1 className="display text-6xl lg:text-8xl leading-[.95] mb-6">{t('hero.title1')}<br/><span className="text-[var(--lime)]">{t('hero.title2')}</span></h1><p className="text-white/65 text-lg leading-8 max-w-xl mb-8">{t('hero.body')}</p><div className="flex flex-wrap gap-3"><a className="btn btn-lime" href="#booking">{t('hero.cta')}</a><a className="btn btn-outline" href="https://wa.me/966573890014"><MessageCircle size={18}/>{t('hero.wa')}</a></div><div className="grid grid-cols-3 gap-6 mt-12 pt-8 border-t border-white/10 max-w-xl"><Stat n="500+" l={t('stats.cats')}/><Stat n="24/7" l={t('stats.monitoring')}/><Stat n="4.9★" l={t('stats.rating')}/></div></motion.div><HeroDashboard ar={ar}/></div></section>
  <section id="about" className="section bg-[#03034A]"><div className="container grid lg:grid-cols-2 gap-12 items-center"><div><div className="eyebrow mb-3">{t('about.label')}</div><h2 className="display text-5xl leading-tight mb-5">{t('about.title')} <span className="text-[var(--lime)]">CatSafe</span></h2><p className="text-white/60 leading-8 text-lg">{t('about.body')}</p><div className="mt-8 space-y-4"><Pillar icon={<Cpu/>} title={ar?'منهج تقني أولًا':'Technology-first approach'} body={ar?'حساسات ولوحات متابعة وتنبيهات مدمجة في كل إقامة.':'Sensors, dashboards and alerts built into every stay.'}/><Pillar icon={<ShieldCheck/>} title={ar?'أمان بدون تنازل':'Safety without compromise'} body={ar?'مراقبة مستمرة وبروتوكولات رعاية واضحة.':'Continuous monitoring and clear care protocols.'}/></div></div><div className="card !p-10 bg-[rgba(185,250,60,.07)] border-[rgba(185,250,60,.22)]"><h3 className="display text-6xl text-[var(--lime)] mb-5">{t('about.mission')}</h3><p className="text-white/65 leading-8 text-lg">{t('about.missionBody')}</p><div className="grid grid-cols-2 gap-4 mt-8"><Mini n="2026" l={ar?'الإطلاق':'Launch'}/><Mini n="Riyadh" l={ar?'المقر':'HQ'}/></div></div></div></section>
  <SectionHeader id="services" label={t('services.label')} title={t('services.title')} body={t('services.body')}/><div className="container grid sm:grid-cols-2 lg:grid-cols-3 gap-5 pb-24">{S.map(([Icon,title,body]:any)=><div className="card hover:border-[rgba(185,250,60,.35)] transition" key={title}><div className="w-14 h-14 rounded-2xl bg-[rgba(185,250,60,.12)] text-[var(--lime)] grid place-items-center mb-5"><Icon/></div><h3 className="font-bold text-xl mb-2">{title}</h3><p className="text-white/55 leading-7">{body}</p></div>)}</div>
  <section id="tech" className="section bg-[#03034A]"><div className="container"><div className="text-center max-w-3xl mx-auto mb-14"><div className="eyebrow mb-3">{t('tech.label')}</div><h2 className="display text-5xl lg:text-6xl leading-tight mb-4">{t('tech.title')}</h2><p className="text-white/60 leading-8 text-lg">{t('tech.body')}</p></div><div className="grid lg:grid-cols-2 gap-5"><Tech icon={<Cpu/>} title={ar?'ذكاء صندوق الرمل':'Smart Litter Box Intelligence'} body={ar?'يراقب الاستخدام والأنماط ويرصد التغييرات المهمة مبكرًا.':'Monitors usage and patterns, catching meaningful changes early.'} accent/><Tech icon={<Activity/>} title={ar?'تتبع السلوك':'Behavioral Tracking'} body={ar?'مؤشرات مستمرة للأكل والنشاط والراحة والمزاج.':'Continuous indicators for food, activity, rest and mood.'}/><Tech icon={<Bell/>} title={ar?'تنبيهات فورية':'Real-Time Notifications'} body={ar?'تأكيدات وتقارير وتنبيهات تصل مباشرة عبر واتساب.':'Confirmations, reports and alerts delivered straight to WhatsApp.'}/><Tech icon={<BarChart3/>} title={ar?'تقارير صحية يومية':'Daily Wellness Reports'} body={ar?'ملخص يومي واضح لحالة القطة ومستوى نشاطها.':'A clear daily summary of your cat’s status and activity.'} accent/></div></div></section>
  <section id="booking" className="section"><div className="container"><div className="text-center max-w-3xl mx-auto mb-14"><div className="eyebrow mb-3">{t('booking.label')}</div><h2 className="display text-5xl lg:text-6xl">{t('booking.title')}</h2></div><div className="grid grid-cols-2 md:grid-cols-7 gap-3 mb-10">{steps.map((s,i)=><div key={s} className={`text-center ${i<2?'text-[var(--lime)]':'text-white/45'}`}><div className={`mx-auto w-12 h-12 rounded-full grid place-items-center display text-xl mb-2 border ${i<2?'bg-[var(--lime)] text-[var(--navy)] border-[var(--lime)]':'border-white/15'}`}>{i+1}</div><div className="text-xs font-bold">{s}</div></div>)}</div><div className="card max-w-2xl mx-auto"><h3 className="display text-3xl mb-1">{t('booking.preview')}</h3><p className="text-white/45 mb-6">{t('booking.sub')}</p><div className="grid sm:grid-cols-2 gap-4 mb-5"><DateBox label={ar?'الدخول':'Check-In'} val={ar?'السبت، 21 يونيو 2026':'Sat, 21 Jun 2026'}/><DateBox label={ar?'الخروج':'Check-Out'} val={ar?'الأربعاء، 25 يونيو 2026':'Wed, 25 Jun 2026'}/></div><button className="btn btn-lime w-full">{t('booking.continue')} →</button></div></div></section>
  <section id="suites" className="section bg-[#03034A]"><div className="container"><div className="text-center max-w-3xl mx-auto mb-14"><div className="eyebrow mb-3">{t('suites.label')}</div><h2 className="display text-5xl lg:text-6xl">{t('suites.title')}</h2></div><div className="grid lg:grid-cols-3 gap-6">{R.map((r,i)=><div key={r[1]} className={`card overflow-hidden ${i===1?'border-[rgba(185,250,60,.45)]':''}`}><div className="text-6xl h-36 rounded-2xl bg-[linear-gradient(135deg,rgba(185,250,60,.16),rgba(255,255,255,.05))] grid place-items-center mb-6 relative">{r[0]}{i===1&&<span className="absolute top-3 end-3 text-xs bg-[var(--lime)] text-[var(--navy)] font-black rounded-full px-3 py-1">POPULAR</span>}</div><h3 className="display text-3xl">{r[1]}</h3><div className="display text-2xl text-[var(--lime)] mb-5">{r[2]} <span className="font-sans text-sm text-white/40">/ night</span></div><ul className="space-y-3 mb-7">{r.slice(3).map(f=><li key={f} className="flex items-center gap-2 text-white/65"><Check size={16} className="text-[var(--lime)]"/>{f}</li>)}</ul><button className={`btn w-full ${i===1?'btn-lime':'btn-outline'}`}>{t('suites.select')}</button></div>)}</div></div></section>
  <section className="section"><div className="container grid lg:grid-cols-2 gap-12 items-center"><Phone ar={ar}/><div><div className="eyebrow mb-3">{t('whatsapp.label')}</div><h2 className="display text-5xl leading-tight mb-5">{t('whatsapp.title')}</h2><p className="text-white/60 leading-8 text-lg mb-8">{t('whatsapp.body')}</p><div className="space-y-4"><Pillar icon={<MessageCircle/>} title={ar?'تأكيد الوصول':'Check-In Confirmation'} body={ar?'رسالة فورية عند وصول قطتك بأمان.':'Instant message when your cat arrives safely.'}/><Pillar icon={<Activity/>} title={ar?'تقارير يومية':'Daily Activity Reports'} body={ar?'الأكل واللعب والراحة وصندوق الرمل في ملخص واحد.':'Food, play, rest and litter box activity in one summary.'}/></div></div></div></section>
  <section className="section bg-[#03034A]"><div className="container"><div className="text-center max-w-3xl mx-auto mb-14"><div className="eyebrow mb-3">{t('why.label')}</div><h2 className="display text-5xl lg:text-6xl">{t('why.title')}</h2></div><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-5">{W.map(([Icon,title,body]:any)=><div className="card text-center" key={title}><Icon className="mx-auto text-[var(--lime)] mb-4" size={36}/><h3 className="font-bold text-xl mb-2">{title}</h3><p className="text-white/50 leading-7">{body}</p></div>)}</div></div></section>
  <section className="section"><div className="container"><div className="text-center max-w-3xl mx-auto mb-14"><div className="eyebrow mb-3">{t('testimonials.label')}</div><h2 className="display text-5xl lg:text-6xl">{t('testimonials.title')}</h2></div><div className="grid lg:grid-cols-3 gap-5">{['Noura Al-Rashidi','Faisal Al-Qahtani','Sara Al-Otaibi'].map((n,i)=><div className="card" key={n}><div className="flex text-[var(--lime)] gap-1 mb-4">{Array.from({length:5}).map((_,j)=><Star key={j} fill="currentColor" size={16}/>)}</div><p className="text-white/70 leading-7 italic mb-6">{ar?'تجربة ممتازة ومريحة. التحديثات عبر واتساب والمراقبة الذكية أعطتني ثقة كاملة أثناء السفر.':'Excellent and comforting experience. WhatsApp updates and smart monitoring gave me complete confidence while traveling.'}</p><div className="font-bold">{n}</div><div className="text-white/40 text-sm">Riyadh · Verified Guest</div></div>)}</div></div></section>
  <section id="faq" className="section bg-[#03034A]"><div className="container max-w-3xl"><div className="text-center mb-12"><div className="eyebrow mb-3">{t('faq.label')}</div><h2 className="display text-5xl">{t('faq.title')}</h2></div>{faqs.map(([q,a],i)=><div className="border-b border-white/10 py-5" key={q}><button onClick={()=>setFaq(faq===i?-1:i)} className="w-full flex justify-between items-center text-start gap-4 font-bold"><span>{q}</span><ChevronDown className={`text-[var(--lime)] transition ${faq===i?'rotate-180':''}`}/></button>{faq===i&&<p className="text-white/55 leading-7 mt-3">{a}</p>}</div>)}</div></section>
  <section className="bg-[var(--lime)] text-[var(--navy)] py-20"><div className="container text-center"><h2 className="display text-5xl lg:text-7xl leading-none mb-5">{t('cta.title')}</h2><p className="text-[rgba(4,4,94,.65)] text-lg mb-8">{t('cta.body')}</p><div className="flex justify-center flex-wrap gap-3"><a className="btn bg-[var(--navy)] text-[var(--lime)]" href="#booking">{t('cta.book')}</a><a className="btn border-2 border-[var(--navy)] text-[var(--navy)]" href="#suites">{t('cta.suites')}</a></div></div></section>
  <footer className="section !pb-10 bg-[#03034A]"><div className="container grid lg:grid-cols-4 gap-10 mb-10"><div className="lg:col-span-2"><div className="display text-3xl mb-3">🐱 CatSafe</div><p className="text-white/50 leading-7 max-w-md">{t('footer.desc')}</p><div className="mt-5 text-white/60 space-y-2"><div>0573890014</div><div>info@catsafe.sa</div><div>catsafe.sa</div></div></div><FooterCol title={ar?'الخدمات':'Services'} items={ar?['فندقة ذكية','أجنحة فاخرة','رعاية يومية','تجميل','نقل']:['Smart Boarding','Luxury Suites','Daily Care','Grooming','Transportation']}/><FooterCol title={ar?'الشركة':'Company'} items={ar?['عن CatSafe','التقنية','الأسعار','الأسئلة','تواصل معنا']:['About','Technology','Pricing','FAQ','Contact']}/></div><div className="container pt-7 border-t border-white/10 flex flex-col sm:flex-row justify-between gap-3 text-white/35 text-sm"><span>{t('footer.rights')}</span><span className="text-[var(--lime)]/70 font-bold">{t('footer.tag')}</span></div></footer>
  <a href="https://wa.me/966573890014" className="fixed bottom-6 end-6 w-14 h-14 rounded-full bg-[#25D366] grid place-items-center shadow-2xl z-50"><MessageCircle/></a>
 </main>
}
function Stat({n,l}:{n:string,l:string}){return <div><div className="display text-3xl text-[var(--lime)]">{n}</div><div className="text-white/45 text-xs mt-1">{l}</div></div>}
function Mini({n,l}:{n:string,l:string}){return <div className="rounded-2xl bg-white/5 p-5 text-center"><div className="display text-3xl text-[var(--lime)]">{n}</div><div className="text-white/40 text-xs mt-1">{l}</div></div>}
function Pillar({icon,title,body}:{icon:React.ReactNode,title:string,body:string}){return <div className="flex gap-4 p-5 rounded-2xl bg-[rgba(185,250,60,.06)] border border-[rgba(185,250,60,.14)]"><div className="w-12 h-12 rounded-xl bg-[rgba(185,250,60,.14)] text-[var(--lime)] grid place-items-center shrink-0">{icon}</div><div><h3 className="font-bold mb-1">{title}</h3><p className="text-white/55 leading-6 text-sm">{body}</p></div></div>}
function Tech({icon,title,body,accent}:{icon:React.ReactNode,title:string,body:string,accent?:boolean}){return <div className={`card ${accent?'bg-[rgba(185,250,60,.075)] border-[rgba(185,250,60,.22)]':''}`}><div className="text-[var(--lime)] mb-4">{icon}</div><h3 className="display text-3xl mb-2">{title}</h3><p className="text-white/55 leading-7">{body}</p></div>}
function DateBox({label,val}:{label:string,val:string}){return <div className="rounded-2xl bg-white/5 border border-white/10 p-4"><div className="text-white/40 text-xs uppercase tracking-widest mb-1">{label}</div><div className="font-bold">{val}</div></div>}
function SectionHeader({id,label,title,body}:{id:string,label:string,title:string,body:string}){return <section id={id} className="pt-24 pb-14"><div className="container text-center max-w-3xl"><div className="eyebrow mb-3">{label}</div><h2 className="display text-5xl lg:text-6xl mb-4">{title}</h2><p className="text-white/60 leading-8 text-lg">{body}</p></div></section>}
function HeroDashboard({ar}:{ar:boolean}){return <motion.div initial={{opacity:0,scale:.96}} animate={{opacity:1,scale:1}} className="space-y-4"><div className="glass rounded-[32px] p-7"><div className="flex justify-between mb-5"><b>{ar?'لوحة CatSafe':'CatSafe Dashboard'}</b><span className="text-[var(--lime)] text-sm font-bold flex gap-2 items-center"><span className="w-2 h-2 rounded-full bg-[var(--lime)]"/> LIVE</span></div>{['Luna','Simba'].map((n,i)=><div key={n} className={`flex items-center gap-3 rounded-2xl border border-[rgba(185,250,60,.2)] bg-[rgba(185,250,60,.08)] p-4 mb-3 ${i?'opacity-70':''}`}><div className="w-12 h-12 rounded-xl bg-[rgba(185,250,60,.18)] grid place-items-center text-2xl">{i?'🐈':'🐱'}</div><div className="flex-1"><div className="font-bold">{n}</div><div className="text-white/45 text-sm">{i?'VIP Suite':'Suite 3B'} · {ar?'اليوم':'Day'} {i+1}</div></div><span className="text-xs text-[var(--lime)] font-black">{i? (ar?'يرتاح':'Resting'):(ar?'نشط':'Active')}</span></div>)}<div className="grid grid-cols-3 gap-3 mt-4"><Mini n="98%" l={ar?'الصحة':'Wellness'}/><Mini n="3x" l={ar?'الصندوق':'Litter'}/><Mini n="2h" l={ar?'لعب':'Play'}/></div></div><div className="glass rounded-3xl p-5 flex gap-4 border-[#25D366]/25 bg-[#25D366]/10"><div className="w-11 h-11 rounded-full bg-[#25D366] grid place-items-center"><MessageCircle/></div><div><div className="text-[#25D366] font-bold text-sm">CatSafe · Smart Alert</div><p className="text-white/75 text-sm leading-6">{ar?'✅ تقرير لونا اليومي جاهز. الأكل ممتاز ونشاط صندوق الرمل طبيعي.':'✅ Luna’s daily report is ready. Ate well and litter box activity is normal.'}</p></div></div></motion.div>}
function Phone({ar}:{ar:boolean}){return <div className="mx-auto max-w-[320px] rounded-[34px] glass p-4"><div className="rounded-2xl bg-[#075E54] p-4 flex gap-3 items-center"><div className="w-10 h-10 rounded-full bg-[var(--lime)] text-[var(--navy)] display grid place-items-center">CS</div><div><b>CatSafe</b><div className="text-white/60 text-xs">Online</div></div></div><div className="p-3 space-y-3">{[ar?'✅ وصلت لونا بأمان واستقرت في الجناح.':'✅ Luna has checked in and settled into her suite.',ar?'🍽️ أنهت وجبتها والنشاط طبيعي.':'🍽️ She finished breakfast and activity is normal.',ar?'كيف وضعها الآن؟':'How is she doing?',ar?'رائعة 😸 درجة الصحة 98٪ ولا توجد ملاحظات.':'She’s doing great 😸 Wellness score: 98%.'].map((m,i)=><div key={m} className={`rounded-2xl p-3 text-sm leading-6 max-w-[85%] ${i===2?'ms-auto bg-[#25D366] text-[var(--navy)]':'bg-[#075E54] text-white'}`}>{m}<div className="text-[10px] opacity-60 mt-1 text-end">{i+9}:02 ✓✓</div></div>)}</div></div>}
function FooterCol({title,items}:{title:string,items:string[]}){return <div><h3 className="font-bold uppercase tracking-widest text-white/45 text-xs mb-4">{title}</h3><ul className="space-y-3 text-white/55">{items.map(i=><li key={i}><a href="#" className="hover:text-[var(--lime)]">{i}</a></li>)}</ul></div>}
